### PR TITLE
Add support for fast dormancy

### PR DESCRIPTION
**Pull request by Flohack74**
This seems to have been missed when migrating from rilmodem to ril driver. Lets try to add this to see if it helps to save power consumption.

### CODE REVIEW

**Comment by peat-psuwit** [comment]
A few questions:
- Do we have to query the value of fast dormancy on `_probe()`?
- This seems like something which is upstream-able. Could you please investigate that? What's the solution SailfishOS uses? (@NotKit ?)

**Comment by Flohack74** [comment]
@peat-psuwit for the probe question, can you point me to the code, I am not seeing this...
For number 2, yes I am already in contact with SFOS and smonich. But, maybe upstream is not interested anymore, they recently switched from ofono-ril-binder-plugin to ofono-binder-plugin. In his own words:

_IRadio@1.0 was essentially a binder version of good old ril socket api, so I introduced a notion of a "transport" plugin for libgrilio. ofono-ril-binder-plugin was such a transport which translated api requests into binder transaction rather than ril socket packets. ofono ril plugin remained largely unchanged, and it retained the ability to work over either binder or ril sockets, depending on configuration and presence of ofono-ril-binder-plugin.
But then IRadio interfaces evolved and started to support things that had no equivalent in the ril socket world. More importantly at some point IRadioConfig interface got involved too. Ofono ril plugin was split into a binary (separately installable) ofono-ril-plugin plugin and ofono-binder-plugin was born._

In this context parts were rewritten and they might have already included that stuff. But yeah, probably we DO NOT MERGE here (was mostly to test CI and get valid packages) and try to open a PR upstream.

**Comment by peat-psuwit** [comment]
> @peat-psuwit for the probe question, can you point me to the code, I am not seeing this...

Ok, apparently Canonical's rilmodem set fast dormancy to `FALSE` on `_probe()`. I suspect there might be no way to query that from modem?

https://github.com/ubports/ofono/blob/xenial/drivers/rilmodem/radio-settings.c#L934

But the idea is the same: make sure our value matches reality.

> For number 2, yes I am already in contact with SFOS and smonich. But, maybe upstream is not interested anymore, they recently switched from ofono-ril-binder-plugin to ofono-binder-plugin. <...>

From a quick inspection, I think the code you touched is moved to ofono-ril-plugin. So upstream PR, at least of this version, should go to that [1]. Does the binder version have the concept of fast dormancy or similar though...

> But yeah, probably we DO NOT MERGE here (was mostly to test CI and get valid packages) and try to open a PR upstream.

I guess you can put this PR into a draft.

[1] Also worth noting is that I think @NotKit is also planning the upgrade to the split version, so you might want to talk to him.

**Comment by Flohack74** [comment]
Yeah I can initialize the value accordingly. The rest is fine, though I do not expect the split would happen on xenial. Unfortunately Github cannot put released PRs to Draft status I think.

**Comment by peat-psuwit** [comment]
The link to convert to a draft is under the reviewer section. Anyway I've done it for you.

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Unfortunately, due to limitations, we're unable to migrate this PR automatically, and we don't have capacity to migrate this PR manually either. If this PR is still relevant, please submit a new MR at:

https://gitlab.com/ubports/development/core/packaging/ofono-sailfish

Sorry for your inconvenience.

**Pull request closed without merging**
