### PR TITLE
rilmodem: radio-settings: implement legacy cap switch

### PR DESCRIPTION
**Pull request by peat-psuwit**
In older versions of RIL (and some newer ones), capability switch can be
done simply by setting the other slot's preferred network to GSM. This
commit automates the preference change in other slots to make sure that
the current preference setting will succeed.

To control whether the device (with newer RIL) uses the legacy
capability switch or not, a new environment variable "OFONO_RIL_LEGACY_
CAP_SWITCH" is introduced. When this environment variable is set to non-
zero value, the legacy capability switch will be used. (I intended to auto-
detect this in `rild` upstart job using the property.)

As this is essentially what qcommsimmodem's radio-settings atom does,
I've decided to also remove that to reduce device-specific code. Note that
I don't have the original device that uses this modem anymore (LG L90
Dual -- mine is broken), so I can't test it out on actual hardware.

This has been tested on FP2 with the work-in-progress Halium 7.1-based
port. However, I believe this should also help FP2 with original 5.1-based
port. Please try if you can set one SIM slot to 3G/4G while the other is
already at 3G/4G successfully.

### CODE REVIEW

**Review by mariogrip — APPROVED** [review]
LGTM :+1: 

But does needs some qa testing before merging

**Comment by UniversalSuperBox** [comment]
Seems to work with the Fairphone 2 on the existing port. Put one at 4G, the other switches to 2G. Easy.

Will the changes to the Upstart job work correctly on devices without Android?

**Comment by peat-psuwit** [comment]
> Will the changes to the Upstart job work correctly on devices without Android?

I guess the rild unit already doesn't work on non-Android devices. It waits for the rild socket to appear, which non-Android devices won't have. However, it may not be relevant because non-Android devices don't (or shouldn't) have `lxc-android-config` installed anyway.

**Comment by UniversalSuperBox** [comment]
That's what I get for reviewing PRs at 8PM at night.

**Review by UniversalSuperBox — APPROVED** [review]
Looks good in my testing and it sounds like non-Qualcomm devices follow a different code path anyway. Let's do it!

**Comment by UniversalSuperBox** [comment]
Notes for QA: On your FP2 with two SIM cards inserted (other devices should not be affected), try to switch mobile data on one SIM to 4G. The other should automatically switch to 2G.

**Comment by PeterNerlich** [comment]
> (other devices should not be affected)

In general? Is no QA required from other devices for this issue at all?

**Comment by Flohack74** [comment]
It needs to work on any 2-SIM device, but so far we do not have many of that. Also, it depends on the baseband, E5 and E4.5 are MTK so probably not affected. So the only device we currently have for testing is FP2.

**Pull request merged**
